name: GitHub Pages deployment

on:
  push:
    branches:
      - main

jobs:
  compilation:
    runs-on: ubuntu-20.04
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run
      - name: Deployment
        run: npm run gh-pages